### ISSUE TITLE
ProxProx Error

### ISSUE THREAD

**Issue by voltexde** [GoMint/ProxProx#45] opened 2018-12-02 20:55 UTC
```
2018-12-02 15:45:05.513 [epollEventLoopGroup-2-1] INFO  io.gomint.proxprox.network.SocketEventListener - Disconnected upstream: -5103294006075260989
2018-12-02 15:45:05.513 [epollEventLoopGroup-2-1] INFO  io.gomint.proxprox.network.DownstreamConnection - Disconnecting DownStream for e26a0394-2856-3d54-8cec-515c644a05d1
2018-12-02 15:45:05.517 [TCP Threads] INFO  io.gomint.proxprox.network.UpstreamConnection - Connected to 127.0.0.1:14001
2018-12-02 15:45:05.636 [TCP Threads] ERROR io.gomint.proxprox.network.tcp.ConnectionHandler - Caught exception in connection (connected to 127.0.0.1:14001) handling:
java.lang.NullPointerException
        at io.gomint.proxprox.network.UpstreamConnection.flushSendQueue(UpstreamConnection.java:836) ~[ProxProx.jar:?]
        at io.gomint.proxprox.network.tcp.ConnectionHandler.channelRead0(ConnectionHandler.java:66) ~[ProxProx.jar:?]
        at io.gomint.proxprox.network.tcp.ConnectionHandler.channelRead0(ConnectionHandler.java:16) ~[ProxProx.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [ProxProx.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [ProxProx.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [ProxProx.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [ProxProx.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [ProxProx.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [ProxProx.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [ProxProx.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [ProxProx.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [ProxProx.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797) [ProxProx.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [ProxProx.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [ProxProx.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [ProxProx.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by Shad0wCore** [comment] 2018-12-02 20:59
This issue is a duplicate of #40

**Closed by Shad0wCore** 2018-12-02 20:59 UTC
